version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.9  # Specify the Python version you want to use
    commands:
      # Install Robot Framework and required libraries
      - echo Installing Robot Framework and dependencies...
      - pip install --upgrade pip
      - python3 -m pip install --upgrade pip
      - pip3 install robotframework robotframework-requests
      # Install AWS CLI
      - echo Installing AWS CLI...
      - pip3 install awscli

  pre_build:
    commands:
      # Confirm installed versions
      - echo Checking installed versions...
      - python3 --version
      - pip3 --version
      - aws --version
      - echo "Setting date variables..."
      # Get current date in YYYY-MM-DD format
      - export CURRENT_DATE=$(date +%F)
      

  build:
    commands:
      # Run Robot Framework tests
      - echo "Running Robot Framework test cases..."
      - robot login_tests.robot

  post_build:
    commands:
      # Display test results
      - echo "Build completed. Uploading results to S3 with date-based folder structure..."
      # Upload results to S3 bucket in a folder based on the current date
      - aws s3 cp output.xml s3://mytestresultsxxx1/$CURRENT_DATE/output.xml
      - aws s3 cp report.html s3://mytestresultsxxx1/$CURRENT_DATE/report.html
      - aws s3 cp log.html s3://mytestresultsxxx1/$CURRENT_DATE/log.html

artifacts:
  files:
    - output.xml
    - report.html
    - log.html
  discard-paths: no
